In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)

Addition: [5 7 9]


In [ ]:
import numpy as np
a = np.array([10, 20, 30])
b = np.array([5, 10, 15])
print("Subtraction:", a - b)

Subtraction: [ 5 10 15]


In [ ]:
import numpy as np
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])
print("Multiplication:", a * b)

Multiplication: [10 18 28]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print("Add 10:", arr + 10)

Add 10: [11 12 13]


In [ ]:
import numpy as np
arr = np.array([2, 4, 6])
print("Multiply by 3:", arr * 3)

Multiply by 3: [ 6 12 18]


In [ ]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr)
print("Element [1,1]:", arr[1,1])

2D Array:
 [[1 2]
 [3 4]]
Element [1,1]: 4


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("Matrix Addition:\n", a + b)

Matrix Addition:
 [[ 6  8]
 [10 12]]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(a, b))

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
print("Determinant:", np.linalg.det(a))

Determinant: -2.0000000000000004


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
print("Inverse:\n", np.linalg.inv(a))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print("Original Array:", arr)
print("Transpose:", arr.T)
print("Shape:", arr.shape)

Original Array: [1 2 3 4]
Transpose: [1 2 3 4]
Shape: (4,)


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original Matrix:\n", arr)
print("Transpose:\n", arr.T)
print("Original Shape:", arr.shape)
print("Transpose Shape:", arr.T.shape)

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Original Shape: (2, 3)
Transpose Shape: (3, 2)


In [ ]:
import numpy as np
arr1 = np.array([3, 4])
print("1D Array:", arr1)
print("Norm of 1D:", np.linalg.norm(arr1))

1D Array: [3 4]
Norm of 1D: 5.0


In [15]:
import numpy as np
arr2 = np.array([[1, 2],
                 [3, 4]])
print("\n2D Array:\n", arr2)
print("Norm of 2D:", np.linalg.norm(arr2))


2D Array:
 [[1 2]
 [3 4]]
Norm of 2D: 5.477225575051661
